class User < ApplicationRecord
    has_secure_password
    has_many :workouts
    has_many :comments, through: :workouts
    validates :username, presence: true
    validates :username, uniqueness: true     
    validates :name, presence: true
    
  # Generate a salted + hashed password and save it to password_digest
  def password=(new_password)
    salt = BCrypt::Engine::generate_salt
    self.password_digest = BCrypt::Engine::hash_secret(new_password, salt)
  end

  # Check the plaintext password against the salted + hashed password
  def authenticate(password)
    # Salts generated by generate_salt are always 29 chars long.
    salt = password_digest[0..28]
    # Compare the saved password_digest against the plaintext password by running the plaintext password through the same hashing function
    return nil unless BCrypt::Engine::hash_secret(password, salt) == self.password_digest
    self
  end

end
